In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dataset_tweet_sentiment_opini_film.csv")
df

Id Sentiment                                         Text Tweet
0      1  negative  Jelek filmnya... apalagi si ernest gak mutu bg...
1      2  negative  Film king Arthur ini film paling jelek dari se...
2      3  negative  @beexkuanlin Sepanjang film gwa berkata kasar ...
3      4  negative  Ane ga suka fast and furious..menurutku kok je...
4      5  negative  @baekhyun36 kan gua ga tau film nya, lu bilang...
..   ...       ...                                                ...
195  196  positive  Fargo juga adaptasi dari film yang cukup berha...
196  197  positive  637.000 waw ini sangat keren flm horor dng jum...
197  198  positive  @filmziarah film yang tenang dan menghanyutkan...
198  199  positive  Film yg amat menarik. Kisah cinta & kesetiaan ...
199  200  positive  Nntn @filmziarah , film bagus, ada kali 5 meni...

[200 rows x 3 columns]

In [14]:
df["Sentiment"] = df["Sentiment"].map({"positive":1, "negative":0})
   
df


Id  Sentiment                                         Text Tweet
0      1          0  Jelek filmnya... apalagi si ernest gak mutu bg...
1      2          0  Film king Arthur ini film paling jelek dari se...
2      3          0  @beexkuanlin Sepanjang film gwa berkata kasar ...
3      4          0  Ane ga suka fast and furious..menurutku kok je...
4      5          0  @baekhyun36 kan gua ga tau film nya, lu bilang...
..   ...        ...                                                ...
195  196          1  Fargo juga adaptasi dari film yang cukup berha...
196  197          1  637.000 waw ini sangat keren flm horor dng jum...
197  198          1  @filmziarah film yang tenang dan menghanyutkan...
198  199          1  Film yg amat menarik. Kisah cinta & kesetiaan ...
199  200          1  Nntn @filmziarah , film bagus, ada kali 5 meni...

[200 rows x 3 columns]

In [10]:
import numpy as np
x = [[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]]
x = np.array(x)
reshape1 = x.reshape(x.shape[0], 2, 2)
reshape = reshape.transpose(1,0,2)
print(x)
print(reshape1)
print(reshape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
[[[ 1  2]
  [ 5  6]
  [ 9 10]
  [13 14]]

 [[ 3  4]
  [ 7  8]
  [11 12]
  [15 16]]]


In [ ]:
def softmax(x):
    exp = np.exp(x)
    return exp / np.sum(exp, axis=1, keepdims=True)

In [88]:
import numpy as np
def Feedforward(x):
    matmul = np.matmul
    x = np.array(x)
    dx = x.shape[1]
    dx = dx *4
    w1 = np.random.randn(len(x[0]),dx)
    b1 = np.random.randn(len(x[0]),dx)
    Logits = matmul(x, w1) + b1
    belah = Logits.shape[1]//2
    x1 = Logits[:,:belah]
    x2 = Logits[:,belah:]
    Logits = SwingGlu(x1,x2)
    w2 = np.random.randn(*Logits.shape)
    b2 = np.random.randn()
    linear = matmul(Logits, w2.T) + b2
    output = linear
    return output
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def swish(x):
    return x * sigmoid(x)    
def SwingGlu(x1,x2):
    return  x2 * swish(x1) 

In [89]:
import numpy as np
x = [[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]]
x= np.array(x)
dx = x.shape[1]

print(Feedforward(x).shape)






(4, 4)


In [ ]:
import numpy as np
import pandas as pd
import re
def embedding_matriks(vocab, d):
    embedding = {} 
    for kata in vocab:
        embedding[kata] = np.random.randn(d)
    return embedding

def tokenize(texts):
    vocab = set()
    for text in texts:
        vocab.update(text.split())
    vocab = list(vocab)
    vocab_size = len(vocab)
    tokenized_texts = []
    for text in texts:
        tokens = tokens.split()
        tokenized_texts.append(tokens)
    return vocab, tokenized_texts

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)
    return text

data = pd.read_csv("file_baru.csv")
data["Clean"] = data["Text Tweet"].apply(clean_text) 
texts = data["Clean"].tolist()
labels =  data["Sentiment"].tolist()
d = 512


token = []
for i in texts:
    token.append(i.split())
panjang_kalimat = []
for i in token:
    panjang_kalimat.append(len(i))
max_len = max(len_token)

x = np.zeros((len(texts), max_len), dtype=int)
for i , kalimat in enumerate(token):
    for j, kata in enumerate(token[i]):
        batas = min(len(kata), max_len)
        x[i, :batas] = kata[:batas]
print(x)
    
    
   
# for i, text in enumerate(token):
#     print(i, text)

    















ValueError: invalid literal for int() with base 10: 'jelek'

In [48]:

vocab = {} 
for i in corpus:
        for j in i: 
            chars = list(j) + ['</w>'] 
            token_tuple = tuple(chars) 
            if token_tuple in vocab: 
                vocab[token_tuple] += 1
            else:
                vocab[token_tuple] = 1 
                print(vocab)
    
                
    # while True:
        new_vocab = {}
        pair_freq = {} 
        for token, freq in vocab.items():   
            for i in range(len(token)-1):  
                pair = (token[i], token[i+1]) 
                if pair in pair_freq: 
                    pair_freq[pair] += freq
                else:
                    pair_freq[pair] = freq
        
        best_pair  = max(pair_freq, key=pair_freq.get )
       
        new_token = []
        for token, freq in list(vocab.items()):
            for i in range(len(token)-1):

                npair =  token[i] + token[i+1]
                if npair == best_pair:
                    new_token.append(npair)
                else :
                    new_token.append(token[i])

        new_token = tuple(new_token)
        new_vocab[new_token] = freq
        vocab = new_vocab
        del new_vocab

    



            
                   
                   
               
                    
                    

                
           





    


      





{('a', 'k', 'u', '</w>'): 1}
{('a', 'k', 'u', '</w>'): 1, ('s', 'u', 'k', 'a', '</w>'): 1}
{('a', 'k', 'u', '</w>'): 1, ('s', 'u', 'k', 'a', '</w>'): 1, ('m', 'a', 'k', 'a', 'n', '</w>'): 1}
{('a', 'k', 'u', '</w>'): 1, ('s', 'u', 'k', 'a', '</w>'): 1, ('m', 'a', 'k', 'a', 'n', '</w>'): 1, ('n', 'a', 's', 'i', '</w>'): 1}
{('a', 'k', 'u', 's', 'u', 'k', 'a', 'm', 'a', 'k', 'a', 'n', 'n', 'a', 's', 'i'): 1, ('d', 'i', 'a', '</w>'): 1}
{('a', 'k', 'u', 's', 'u', 'k', 'a', 'm', 'a', 'k', 'a', 'n', 'n', 'a', 's', 'i'): 1, ('d', 'i', 'a', '</w>'): 1, ('s', 'u', 'k', 'a', '</w>'): 1}
{('a', 'k', 'u', 's', 'u', 'k', 'a', 'm', 'a', 'k', 'a', 'n', 'n', 'a', 's', 'i'): 1, ('d', 'i', 'a', '</w>'): 1, ('s', 'u', 'k', 'a', '</w>'): 1, ('m', 'a', 'k', 'a', 'n', '</w>'): 1}
{('a', 'k', 'u', 's', 'u', 'k', 'a', 'm', 'a', 'k', 'a', 'n', 'n', 'a', 's', 'i'): 1, ('d', 'i', 'a', '</w>'): 1, ('s', 'u', 'k', 'a', '</w>'): 1, ('m', 'a', 'k', 'a', 'n', '</w>'): 1, ('a', 'y', 'a', 'm', '</w>'): 1}


In [1]:
corpus = [["aku", "suka", "dimana", "nasi"], ["nasi", "dimakan", "ayam"], ["makan", "dimeja" ,"makan"]]
def tokenizer(corpus):
    vocab = {}
    for kalimat in corpus:
        for kata in kalimat:
            char = list(kata) + ["</w>"]
            char = tuple(char)
            if char in vocab:
                vocab[char] += 1
            else:
                vocab[char] = 1
    while True:
        pair_freq = {}
        for token, freq in vocab.items():
            for i in range(len(token) - 1):
                pair = (token[i], token[i+1])
                if pair in pair_freq:
                    pair_freq[pair] += freq
                else:
                    pair_freq[pair] = freq
        best_value = max(pair_freq.values())
        best_pair = max(pair_freq, key=pair_freq.get)

        if best_value < 2:
            break

        new_vocab = {}
        for token, freq in vocab.items():
            new_token = []
            i = 0
            while i < len(token):
                if i < len(token) - 1 and (token[i], token[i+1]) == best_pair:
                    new_token.append(token[i] + token[i+1])
                    new_vocab[tuple(new_token)] = freq
                    i += 2

                else:
                    new_token.append(token[i])
                    i += 1
                new_vocab[tuple(new_token)] = freq

        vocab = new_vocab
        vocab_index = {}
        for i, token in enumerate(vocab.keys()):
            vocab_index[token] = i
        
    return vocab_index

    
vocab = tokenizer(corpus)

print(vocab)
print(corpus)




{('ak',): 0, ('aku',): 1, ('aku', '</w>'): 2, ('s',): 3, ('su',): 4, ('suk',): 5, ('suka',): 6, ('suka', '</w>'): 7, ('d',): 8, ('di',): 9, ('dim',): 10, ('dima',): 11, ('dima', 'n'): 12, ('dimana',): 13, ('dimana', '</w>'): 14, ('n',): 15, ('na',): 16, ('nas',): 17, ('nasi',): 18, ('nasi</w>',): 19, ('dim', 'ak'): 20, ('dim', 'aka'): 21, ('dimakan',): 22, ('dimakan', '</w>'): 23, ('a',): 24, ('ay',): 25, ('aya',): 26, ('ayam',): 27, ('ayam', '</w>'): 28, ('m',): 29, ('mak',): 30, ('maka',): 31, ('makan',): 32, ('makan</w>',): 33, ('dime',): 34, ('dimej',): 35, ('dimeja',): 36, ('dimeja', '</w>'): 37}
[['aku', 'suka', 'dimana', 'nasi'], ['nasi', 'dimakan', 'ayam'], ['makan', 'dimeja', 'makan']]


In [ ]:
def flatten_vocab(vocab):
    token_set = set()
    for token_tuple in vocab.keys():
        for t in token_tuple:
            token_set.add(t)
            
    vocab_dict = {token: idx for idx, token in enumerate(sorted(token_set))}
    vocab_dict["[UNK]"] = len(vocab_dict)  # optional: token unknown
    return vocab_dict

vocab_dict = flatten_vocab(vocab)
print(vocab_dict)


{'</w>': 0, 'a': 1, 'ak': 2, 'aka': 3, 'aku': 4, 'ay': 5, 'aya': 6, 'ayam': 7, 'd': 8, 'di': 9, 'dim': 10, 'dima': 11, 'dimakan': 12, 'dimana': 13, 'dime': 14, 'dimej': 15, 'dimeja': 16, 'm': 17, 'mak': 18, 'maka': 19, 'makan': 20, 'makan</w>': 21, 'n': 22, 'na': 23, 'nas': 24, 'nasi': 25, 'nasi</w>': 26, 's': 27, 'su': 28, 'suk': 29, 'suka': 30, '[UNK]': 31}


In [24]:
import torch
from torch.nn.utils.rnn import pad_sequence

def encode_word(word, vocab_dict):
    tokens = list(word) + ["</w>"]
    while True:
        merged = False
        for i in range(len(tokens)-1):
            pair = tokens[i] + tokens[i+1]
            if pair in vocab_dict:
                tokens = tokens[:i] + [pair] + tokens[i+2:]
                merged = True
                break
        if not merged:
            break

    token_ids = []
    for t in tokens:
        if t in vocab_dict:
            token_ids.append(vocab_dict[t])
        else:
            for c in t:
                if c in vocab_dict:
                    token_ids.append(vocab_dict[c])
                else:
                    token_ids.append(vocab_dict['[UNK]'])
    return token_ids

def encode_corpus(corpus, vocab_dict):
    encoded = []
    for sentence in corpus:
        encoded_sentence = []
        for word in sentence:
            encoded_sentence.extend(encode_word(word, vocab_dict))
        encoded.append(encoded_sentence)
    return encoded

# contoh corpus
token = encode_corpus(corpus, vocab_dict)
print(corpus)
print(vocab_dict)
max_len = len(max(token))
print(token)



    # ubah list jadi tensor satu per satu
tensor_token = [torch.tensor(seq) for seq in token]

# padding jadi batch tensor
padded_batch = pad_sequence(tensor_token, batch_first=True, padding_value=0)

print(padded_batch)
d = 64





[['aku', 'suka', 'dimana', 'nasi'], ['nasi', 'dimakan', 'ayam'], ['makan', 'dimeja', 'makan']]
{'</w>': 0, 'a': 1, 'ak': 2, 'aka': 3, 'aku': 4, 'ay': 5, 'aya': 6, 'ayam': 7, 'd': 8, 'di': 9, 'dim': 10, 'dima': 11, 'dimakan': 12, 'dimana': 13, 'dime': 14, 'dimej': 15, 'dimeja': 16, 'm': 17, 'mak': 18, 'maka': 19, 'makan': 20, 'makan</w>': 21, 'n': 22, 'na': 23, 'nas': 24, 'nasi': 25, 'nasi</w>': 26, 's': 27, 'su': 28, 'suk': 29, 'suka': 30, '[UNK]': 31}
[[4, 0, 30, 0, 13, 0, 26], [26, 11, 31, 1, 22, 0, 7, 0], [21, 16, 0, 21]]
tensor([[ 4,  0, 30,  0, 13,  0, 26,  0],
        [26, 11, 31,  1, 22,  0,  7,  0],
        [21, 16,  0, 21,  0,  0,  0,  0]])


In [ ]:
import numpy as np
def embedding_matriks(vocab, d):
    embedding = np.array(np.random.randn(len(vocab), d))
    return embedding

e_matriks = embedding_matriks(vocab_dict, d)
print(e_matriks.shape)

def word_embedding(batch_size, len_token, e_matriks):
    embedding_matriks = embedding[batch]
    return embedding_matriks 

embedding = word_embedding(padded_batch, e_matriks)
print(embedding)

Z






(32, 64)


NameError: name 'batch' is not defined

In [52]:
def isPalindrome (x: int):
       yam =list(str(x))
       yam = [int(i) for i in yam ]
       for i in (yam):
        print(-i-1)
        if yam[i] == yam[-i-1]:
         return True
        else:
         return False
       
       


x = 121
x = isPalindrome(x)
print(x)

-2
True


In [ ]:
def romanToInt(s: str) -> int:
    roman = { 'I':1, 'V':5, 'X':10, 'L':50, 'C':100, 'D':500, 'M':1000}

    total = 0
    prev = 0
    for i in reversed(s):
        curr = roman[i]
        if curr < prev:
            total -= curr
        else:
            total += curr
        prev = curr

    return total 
            
                
        
                
    
S = "VIII"
chi = romanToInt(S)
print(chi)

    

8


In [53]:
s = "ABCD"
for i in (s):
    print(i)
print(s)

A
B
C
D
ABCD


In [ ]:
def isValid( s: str) -> bool:
    pair = {')': '(', ']': '[', '}': '{'}
    total = []
    for i in s:
        if i == '(' or i == '{' or i == '[':
            total.append(i)
        elif i == ')' or i == '}' or i == ']':
            if total[-1]  == pair[i]:
                total.pop()
            else:
                return False
    if len(total) == 0:
        return True
    else:
        return False
    
                

            
        
            



s = "["
C = isValid(s)
print(C)



None


In [108]:
def reverseString( s: [str]) -> None:
        ayam = "".join(reversed(s))
        chik = []
        print(ayam)
        for i in ayam:
            chik.append(i)
        print(chik)
        return chik
    
s= ["h","e","l","l","o"]
print(reverseString(s))

olleh
['o', 'l', 'l', 'e', 'h']
['o', 'l', 'l', 'e', 'h']


AttributeError: 'list' object has no attribute 'shape'

In [2]:
import numpy as np

dummy_data = np.random.randint(0, 100, size=(4, 8, 16))
print(dummy_data)


[[[42 35 17 39 31 68 94 76 33 70 95  4 74 59 67  7]
  [ 1 71 54 67 47 80 80 97 72 62 56 38 96  7 12  1]
  [19 81 74 17 32 72 77 49 13  1 73 61 49 39  0 37]
  [72  0 67 76 26 67 23  0 70 95 27 27 95 29 24 29]
  [35 51 30 32 80 75 56  0 31 11 84 26 52  2 96 82]
  [ 1 58 62 95 80 18 40 28 18 97 52 54 18 21  4 69]
  [10 20 20 86 16 17 13 76  6 93 55 70 44 68 47 22]
  [83 58 82 76 78 59 49 78 60 13 30 43 23 61 20 98]]

 [[78 27 14 99 32 61 28  9 40 92 74 20 42 59 81 58]
  [91 65 56 57 46 48  6 88 59 56  0 31 53 99 51 35]
  [10 12 70 80 51 94 25  1 82 75 48 77 63 68 41 22]
  [34 59 97 11 65 59 13 72 78 40  0 73 90 97 13 41]
  [23 44 47 13 89 76 85 27 90 97 37 96 64 19 38 60]
  [99 49 42 23 33  0 34 93 55 88 61 25 47 15 59 38]
  [89 47 86 30 69 81 15 34 15 64 83 74 32 20 84 26]
  [74 35 73 93 30 57 57 19 93 99 16 82 80 12 51 16]]

 [[98 43 56 65  7 45 24 42  7 58 59 54  6 95 65 61]
  [50 17 17 14 16 95 71 69 70 69 97 69 39  6 33 86]
  [93 45 69 30 63 47 11 58 64 33 32 56 48 11 54 12]
  [17 82

In [4]:
w= np.random.rand(*dummy_data.shape)
w = w.reshape(4,8,4,4)
w.shape

(4, 8, 4, 4)

In [ ]:
def rope(x):
    


In [ ]:
def GMHSA(x,d, num_head = 4, head_dim = 8, num_group = 2):
    wq = np.random.randn(d,d)
    wk = np.random.rand(d,d)
    wv = np.random.rand(d,d)

    Q = x @ wq.T 
    K = x @ wk.T
    V = x @ wv.T

    Q = Q.reshape(10,36,2,4,8).transpose(0,2,1,3,4)
    K = K.reshape(10,36,2,4,8).transpose(0,2,1,3,4)
    V = V.reshape(10,36,2,4,8).transpose(0,2,1,3,4)
    
    Q = rope(Q, dims= 2)
    K = rope(K,dims= 2 )

In [1]:
import requests

url = "https://www.gutenberg.org/files/2554/2554-0.txt"
resp = requests.get(url)
resp.raise_for_status()

with open("i.txt", "w", encoding="utf-8") as f:
    f.write(resp.text)

print("✔️ Berhasil menyimpan konten ke i.txt")


✔️ Berhasil menyimpan konten ke i.txt


In [6]:
from BPE_tokenizer import BPETokenizer

corpus = [["hello", "world"], ["hello", "there"], ["world", "there"]]

tokenizer = BPETokenizer(min_pair_freq=2)
tokenizer.fit(corpus)

print("Vocab:", tokenizer.get_vocab())
print("Encoded:", tokenizer.encode(corpus))

Vocab: {'hello</w>': 0, 'world</w>': 1, 'there</w>': 2, '[UNK]': 3}
Encoded: [[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]


In [ ]:
'dim': 256,
'n_layers': 4,
'n_heads': 4,
'n_kv_heads': 2,
'hidden_dim': 768,
'max_seq_len': 128,
'learning_rate': 1e-4,
'weight_decay': 0.01,
'batch_size': 32,
'num_epochs': 5

In [8]:
corpus = [["aku", "makan"], ["aku", "tidur"], ["makan", "nasi"]]

tokenizer = BPETokenizer(min_pair_freq=2)
tokenizer.fit(corpus)

print("Vocab:", tokenizer.get_vocab())

encoded = tokenizer.encode([["aku", "makan"]])
print("Encoded:", encoded)




Vocab: {'aku</w>': 0, 'makan</w>': 1, 'i': 2, '</w>': 3, 't': 4, 'd': 5, 'u': 6, 'r': 7, 'n': 8, 'a': 9, 's': 10, '[UNK]': 11}
Encoded: [[9, 11, 6, 3, 11, 9, 11, 9, 8, 3]]


In [1]:
import pickle

# 1. Load model dari file
with open("bpe_model.pkl", "rb") as f:
    tokenizer = pickle.load(f)

# 2. Dummy data dari dataset
dummy_sentence = [["nasi", "dimakan", "ayam"]]

# 3. Encode

encoded_corpus = tokenizer.encode_corpus(corpus)
print("Encoded:", encoded)




AttributeError: 'dict' object has no attribute 'encode_corpus'

In [14]:
import pickle
import torch

# Load model dari file
try:
    with open("LLama.pkl", "rb") as f:
        model = pickle.load(f)
    print("✅ Berhasil memuat model.")
except Exception as e:
    print("❌ Gagal memuat model:", e)
    exit()
print("Tipe objek:", type(model))
print("Atribut dalam model:", dir(model))

# Set model ke mode evaluasi
model.eval()  # pastikan ini adalah model, bukan tokenizer

# Ambil tokenizer dari dalam model
tokenizer = model.tokenizer  # atau model.BPETokenizer, sesuai struktur kamu

# Input prompt
prompt = "he made his"
input_ids = tokenizer.encode(prompt)
input_tensor = torch.tensor([input_ids], dtype=torch.long)

# Prediksi token selanjutnya
with torch.no_grad():
    logits = model(input_tensor)
    next_token_id = torch.argmax(logits[:, -1], dim=-1).item()
    predicted_token = tokenizer.decode([next_token_id])

print("Prediksi token selanjutnya:", predicted_token)


✅ Berhasil memuat model.
Tipe objek: <class 'llama_from_scratch.BPETokenizer'>
Atribut dalam model: ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'encode', 'encode_word', 'fit', 'vocab', 'vocab_index', 'vocab_size']


AttributeError: 'BPETokenizer' object has no attribute 'eval'

In [25]:
import pickle

try:
    with open("LLama.pkl", "rb") as f:
        obj = pickle.load(f)
    print(" Berhasil memuat file LLama.pkl.")
except Exception as e:
    print(" Gagal memuat file LLama.pkl:", e)


 Berhasil memuat file LLama.pkl.


In [23]:
import pickle

with open("bpe_model.pkl", "rb") as f:
    bpe_model = pickle.load(f)

print(type(bpe_model))
print(dir(bpe_model))




# Tampilkan 10 item pertama
import pickle

with open("llama_model/tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)

vocab =tokenizer.vocab  # token -> id
print(len(vocab))



<class 'dict'>
['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']
9540


In [29]:
from datasets import load_dataset

dataset = load_dataset('squad')

c:\Users\USER DK\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
INFO:datasets:PyTorch version 2.6.0 available.
INFO:datasets:TensorFlow version 2.19.0 available.
c:\Users\USER DK\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\USER DK\.cache\huggingface\hub\datasets--squad. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support 

In [30]:
from datasets import load_dataset
import json

# Load SQuAD v1.1
dataset = load_dataset("squad")

def convert_to_qa_format(dataset_split):
    formatted_data = []
    for sample in dataset_split:
        question = sample["question"].strip()
        context = sample["context"].strip()
        answer = sample["answers"]["text"][0].strip()

        input_text = f"### Question:\n{question}\n\n### Context:\n{context}"
        target_text = answer

        formatted_data.append({
            "input": input_text,
            "target": target_text
        })

    return formatted_data

# Convert train and validation
train_data = convert_to_qa_format(dataset["train"])
val_data = convert_to_qa_format(dataset["validation"])

# Save ke file JSON
with open("squad_train_qa.json", "w", encoding="utf-8") as f:
    json.dump(train_data, f, indent=2, ensure_ascii=False)

with open("squad_val_qa.json", "w", encoding="utf-8") as f:
    json.dump(val_data, f, indent=2, ensure_ascii=False)

print("✅ Dataset converted and saved as 'squad_train_qa.json' and 'squad_val_qa.json'")


✅ Dataset converted and saved as 'squad_train_qa.json' and 'squad_val_qa.json'


In [12]:
import pickle
from llama_model.llama_from_scratch import BPETokenizer

with open('llama_model/tokenizer.pkl', 'rb') as f:
    tokenizer = pickle.load(f)

tokenizer = BPETokenizer()
tokenizer.vocab = vocab

text = "hello world"
tokens = tokenizer.encode(text)
print("Token IDs:", tokens)

# Kalau ingin lihat token string-nya (opsional)
decoded = tokenizer.decode(tokens)
print("Decoded:", decoded)






NameError: name 'vocab' is not defined

In [26]:
import pickle

with open("llama_model/tokenizer.pkl", "rb") as f:
    obj = pickle.load(f)
# with open("llama_model/model.pt", "r") as j:
#     obj = pickle.load(j)

print(type(obj))  # Cek tipe data-nya
print(dir(obj))   # Lihat isinya kalau objek
print(obj.vocab)  # ✅ akses langsung dari objek

text = "hello world"
tokens = tokenizer.encode(text)
print("Token IDs:", tokens)

# Tes decode (opsional)
decoded = tokenizer.decode(tokens)
print("Decoded:", decoded)



<class 'llama_model.llama_from_scratch.BPETokenizer'>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'decode', 'encode', 'encode_word', 'fit', 'vocab', 'vocab_index', 'vocab_size']
{'!': 0, '!)</w>': 1, '!--and</w>': 2, '!...</w>': 3, '!...”</w>': 4, '!</w>': 5, '!’</w>': 6, '!”--and</w>': 7, '!”</w>': 8, '(': 9, '(Cough,</w>': 10, '(as</w>': 11, '(for</w>': 12, '(he</w>': 13, '(she</w>': 14, '(which</w>': 15, ')': 16, '),</w>': 17, ').</w>': 18, ')</w>': 19, '*****</w>': 20, '***</w>': 21, ',': 22, ',...</w>': 23, ',</w>': 24, ',’</w>': 25, ',”</w>': 26, '-': 27, '--': 28, '----': 29, '----</w>': 30, '--I</w>': 31, '--a</w>': 32, '--all</w>': 33, '--an</w>': 34, '--and</w>': 3

AttributeError: 'BPETokenizer' object has no attribute 'id_to_token'